apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: misacademy/two-tier:v2
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
        ports:
          - containerPort: 5000  
        envFrom:
          - secretRef:
             name: mysql-secret
          - configMapRef:
             name: mysql-config

